window_border_width 0
window_margin_width 0
window_padding_width 4
single_window_margin_width 0
inactive_text_alpha 0.5
resize_in_steps yes

font_size 12.0

cursor_trail 0

# Performance tuning
sync_to_monitor yes

# Terminal bell
enable_audio_bell yes
window_alert_on_bell yes

# Open windows in pwd
map ctrl+shift+enter new_window_with_cwd

# Open tab in pwd
map ctrl+shift+t new_tab_with_cwd

tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline

# Set the tab title format (shows only the name, no path)
tab_title_template "{index}: {title}"

# Make the tab bar look more modern
tab_bar_style powerline
tab_powerline_style slanted


# BEGIN_KITTY_THEME
# Dracula
include current-theme.conf
background_opacity 0.85
background_blur 1
dynamic_background_opacity 0

selection_foreground none
selection_background none

# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
