theme = "catppuccin_mocha"

[editor]
mouse = true
line-number = "absolute"
auto-completion = true
bufferline = "never"
auto-format = true
cursorline = true
auto-info = true
true-color = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
skip-levels = 1

[editor.file-picker]
hidden = false
