[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format", args = ["--style=Microsoft"]}

[[language]]
name = "python"
language-servers = [ "pylsp" ]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = {command = "npx", args = ["prettier", "--parser", "typescript"]}

[[language]]
name = "tailwindcss"
scope = "source.svelte"
roots = ["tailwind.config.js","tailwind.config.cjs"]
file-types = ["svelte"]
language-servers = ["tailwindcss-language-server","svelte-server"]

[language-server.tailwindcss-svelte]
language-id = "svelte"
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { }
