theme = "ayu_dark"

[editor]
mouse = true
line-number = "absolute"
auto-completion = true
bufferline = "never"
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[editor.file-picker]
hidden = false
