theme = "tokyonight"

[editor]
mouse = true
line-number = "absolute"
auto-completion = true
bufferline = "never"
auto-format = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
# render = true
# character = "|"
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.smart-tab]
enable = false
